name: CI/CD Docker

env:
  CI: false

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Baixa o código
      - name: Checkout código
        uses: actions/checkout@v4

      # Login no Docker Hub
      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build da imagem
      - name: Build da imagem Docker
        # run: docker build -t ${{ secrets.DOCKER_USERNAME }}/apex-gambit:latest .
        run: docker build --progress=plain --no-cache -t apex-gambit .

      # Push para o Docker Hub
      - name: Push para o Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/apex-gambit:latest
